
import 'package:flutter/material.dart';

class IconsHelper {
  static Map<String, IconData> map = {
    'attach_money': Icons.attach_money,
    'abc': Icons.abc,
    'pinpad':Icons.pin_sharp,
    'ipaddress':Icons.wifi,
    'inventory_2_outlined':Icons.inventory_2_outlined,
    'business_outlined':Icons.business_outlined,
    'list_outlined': Icons.list_alt_outlined,
    'factory_outlined': Icons.factory_outlined,
    'store_outlined':Icons.store_outlined,
    'bar_chart_outlined': Icons.bar_chart_outlined,
    'description_outlined': Icons.description_outlined,
    'insert_drive_file_outlined': Icons.insert_drive_file_outlined,
    'work_outline_outlined': Icons.work_outline_outlined,
    'location_city_outlined': Icons.location_city_outlined,
    'computer_outlined': Icons.computer_outlined,
    'trip_origin': Icons.trip_origin,
    'home':Icons.home,
    'receipt':Icons.receipt,
    'people_alt_outlined':Icons.people_alt_outlined,
    'inventory':Icons.inventory,
    'settings':Icons.settings,
    'mail_rounded':Icons.mail_rounded,
    'lock':Icons.lock,
    'userlock':Icons.lock_person_outlined,
    'money_outlined':Icons.money_outlined,
    'article_outlined':Icons.article_outlined,
    'credit_card_outlined':Icons.credit_card_outlined,
    'article':Icons.article,
    'call_missed_outgoing':Icons.call_missed_outgoing,
    'print':Icons.print,
    'history':Icons.history,
    'edit':Icons.edit,
    'atm':Icons.atm_outlined,
    'printing':Icons.print_outlined,
    'delete':Icons.delete,
    'multiple_stop':Icons.multiple_stop,
    'landslide':Icons.landslide,
    'warning_amber':Icons.warning_amber,
    'add':Icons.add,
    'remove':Icons.remove,
    'vertical_align_bottom':Icons.vertical_align_bottom,
    'vertical_align_top':Icons.vertical_align_top,
    'restart_alt':Icons.restart_alt,
    'local_atm':Icons.local_atm,
    'request_quote':Icons.request_quote,
    'fingerprint_outlined':Icons.fingerprint_outlined,
    'style_outlined':Icons.style_outlined,
    'password_outlined':Icons.password_outlined,
    'pin_outlined':Icons.pin_outlined,
    'content_paste_outlined':Icons.content_paste_outlined,
    'pending_actions_outlined':Icons.pending_actions_outlined,
    'time':Icons.access_time_filled,
    'language':Icons.language_outlined,
    'percentage':Icons.percent_outlined,
    'person':Icons.person,
    'terminal':Icons.terminal,
    'product':Icons.add_box_rounded,
    'discount':Icons.discount,
    'repeat':Icons.repeat,
    'return':Icons.keyboard_return,
    'cardvalidation':Icons.credit_score,
    'link':Icons.link,
    'archive':Icons.archive,
    'price_check':Icons.price_check,
    'point_of_sale':Icons.point_of_sale,
    'reset_discount':Icons.restart_alt,
    'tax_free':Icons.safety_check,
    'category':Icons.corporate_fare,
    'local_offer':Icons.local_offer,
    'redeem_outlined':Icons.redeem_outlined,
    'loyalty':Icons.loyalty_outlined,
    'security':Icons.security,
    'barcodereader':Icons.barcode_reader,
    'file_open':Icons.file_open,
    'keyboard':Icons.keyboard,
    'logout':Icons.logout_outlined,
    'notification':Icons.notifications
  };
}