// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwF86qNmx9i-4wjDP0GdUEnD5NTEErviE',
    appId: '1:170603117468:web:3bae25ae6089560344a659',
    messagingSenderId: '170603117468',
    projectId: 'learningapp-fb169',
    authDomain: 'learningapp-fb169.firebaseapp.com',
    storageBucket: 'learningapp-fb169.firebasestorage.app',
    measurementId: 'G-VWQW5DWJQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtL1H53e8kYmgqY7q2WJcgG6lvZoKfnJA',
    appId: '1:170603117468:android:5c4be9d4cf8bcd0044a659',
    messagingSenderId: '170603117468',
    projectId: 'learningapp-fb169',
    storageBucket: 'learningapp-fb169.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpoPFFt2u1AryGjvPBY3_uaG48LyLIj18',
    appId: '1:170603117468:ios:13d63f7465806c1f44a659',
    messagingSenderId: '170603117468',
    projectId: 'learningapp-fb169',
    storageBucket: 'learningapp-fb169.firebasestorage.app',
    androidClientId: '170603117468-76qpapaihpb732aid9jrhlpts5va6jrl.apps.googleusercontent.com',
    iosClientId: '170603117468-3d4t0l9e58q9ie5jsboh9cgcvfpk7jmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpoPFFt2u1AryGjvPBY3_uaG48LyLIj18',
    appId: '1:170603117468:ios:13d63f7465806c1f44a659',
    messagingSenderId: '170603117468',
    projectId: 'learningapp-fb169',
    storageBucket: 'learningapp-fb169.firebasestorage.app',
    androidClientId: '170603117468-76qpapaihpb732aid9jrhlpts5va6jrl.apps.googleusercontent.com',
    iosClientId: '170603117468-3d4t0l9e58q9ie5jsboh9cgcvfpk7jmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwF86qNmx9i-4wjDP0GdUEnD5NTEErviE',
    appId: '1:170603117468:web:cd0e3a55d76ed44844a659',
    messagingSenderId: '170603117468',
    projectId: 'learningapp-fb169',
    authDomain: 'learningapp-fb169.firebaseapp.com',
    storageBucket: 'learningapp-fb169.firebasestorage.app',
    measurementId: 'G-277JJGW21V',
  );
}
